### ISSUE TITLE
released downloads is gzip, not zip

### ISSUE THREAD

**Issue by fliar** [yaruopooner/ac-clang#10]
downloads can not be opened directly by windows explorer

**Comment by yaruopooner** [comment]
hi, fliar.

which file?
please tell me URL.

I have tested 4 of the latest zip files,
It was successfully decompress.

**Comment by fliar** [comment]
yes, it could be decompressed, but it's not a regular zip file.
as I know zip file can be opened directly by windows explorer, but when I double-clicked the downloaded zip file, windows explorer could not open it, 7zip confirmed that the file format is gzip, not zip

**Comment by yaruopooner** [comment]
Thanks for the report. I replaced it what was compressed with gzip to zip and uploaded it again. The scope of the target was clang-server 1.5.0 - 1.7.1.
