### ISSUE TITLE
Error building clang-server

### ISSUE THREAD

**Issue by chenhong805** [yaruopooner/ac-clang#3]
Hello , when I tried to build the `clang-server` using `builder_sample.sh`, it gave me `error`:

In file included from /Users/jinhongc/.emacs.d/elpa/ac-clang-20150624.2000/clang-server/main.cpp:31:
/Users/jinhongc/.emacs.d/elpa/ac-clang-20150624.2000/clang-server/./ClangServer.hpp:87:55: error: type 'const ClangServer::Specification' does
      not provide a call operator
    ClangServer( const Specification& Specification = Specification() );
                                                      ^~~~~~~~~~~~~
1 error generated.
make[2]: **\* [CMakeFiles/clang-server.dir/main.cpp.o] Error 1
make[1]: **\* [CMakeFiles/clang-server.dir/all] Error 2
make: **\* [all] Error 2

How can I solve it?

**Comment by yaruopooner** [comment]
Hi,thank you report.

Please tell me your environment.
I want the following information.
-OS
-compiler and version
-CMAKE version
-console log of builder_sample.sh 

This report error not occur in my environment.
- My build environment 1
  OS: win7 pro 64
  compiler: MSVS cl 2013, 2015preview
  cmake : 3.1.3
- My build environment 2
  OS: Ubuntu 14.10-15.04
  compiler: gcc 4.9.2
  cmake : 3.1.0

**Comment by chenhong805** [comment]
The entire `stdout`:

-- The C compiler identification is AppleClang 6.1.0.6020049
-- The CXX compiler identification is AppleClang 6.1.0.6020049
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/jinhongc/.emacs.d/elpa/ac-clang-20150624.2000/build
Scanning dependencies of target clang-server
[ 25%] Building CXX object CMakeFiles/clang-server.dir/main.cpp.o

The entire `stderr`:

env: 
env: CMAKE_CXX_COMPILER_ID = Clang
env: CMAKE_CXX_STANDARD = 
env: CYGWIN = 
env: WIN32 = 
env: UNIX = 1
env: MSVC = 
env: MSVC_VERSION = 
env: CMAKE_GNUtoMS = 
env: CMAKE_SYSTEM_NAME = Darwin
env: CMAKE_COMPILER_IS_GNUC = 
env: CMAKE_COMPILER_IS_GNUCXX = 
env: CMAKE_COMPILER_IS_MINGW = 
env: CMAKE_COMPILER_IS_CYGWIN = 
environment: UNIX
non CYGWIN
IT_SEARCH_PATH : /home/yaruopooner/work/llvm-build-shells/sh/clang-361/build
IT_SEARCH_PATH : /Users/jinhongc/.emacs.d/elpa/ac-clang-20150624.2000/clang-server
not found library
final: 
final: CMAKE_CONFIGURATION_TYPES = Release;RelWithDebInfo;Debug
final: project_configurations = RELEASE;RELWITHDEBINFO;DEBUG
final: CMAKE_GENERATOR = Unix Makefiles
final: CMAKE_HOST_SYSTEM_PROCESSOR = x86_64
final: CMAKE_CURRENT_SOURCE_DIR = /Users/jinhongc/.emacs.d/elpa/ac-clang-20150624.2000/clang-server
final: collected_library_apath = 
final: library_apaths = 
final: CMAKE_CXX_FLAGS =  -std=c++11 -Wall -Wno-unused-result
final: CMAKE_CXX_FLAGS_DEBUG = -g
final: CMAKE_CXX_FLAGS_RELEASE = -O3 -DNDEBUG
final: project_defs = -DCMAKE_GENERATOR="Unix Makefiles";-DCMAKE_HOST_SYSTEM_PROCESSOR="x86_64"
final: CMAKE_EXE_LINKER_FLAGS = -Wl,-rpath,/usr/local/lib/clang-server
final: CMAKE_EXE_LINKER_FLAGS_DEBUG = 
final: CMAKE_EXE_LINKER_FLAGS_RELEASE = 
final: dependency_libraries = libclang
final: binary_destination_apath = /usr/local/bin
final: library_destination_apath = /usr/local/lib/clang-server
final: CMAKE_FIND_LIBRARY_PREFIXES = lib
final: CMAKE_FIND_LIBRARY_SUFFIXES = .dylib;.so;.a
final: CMAKE_INSTALL_PREFIX = /usr/local
final: CMAKE_INSTALL_RPATH = /usr/local/lib/clang-server
final: CMAKE_SKIP_BUILD_RPATH = 
final: CMAKE_BUILD_WITH_INSTALL_RPATH = 
final: CMAKE_SKIP_RPATH = TRUE
final: CMAKE_SKIP_INSTALL_RPATH = NO
In file included from /Users/jinhongc/.emacs.d/elpa/ac-clang-20150624.2000/clang-server/main.cpp:31:
/Users/jinhongc/.emacs.d/elpa/ac-clang-20150624.2000/clang-server/./ClangServer.hpp:87:55: error: type 'const ClangServer::Specification' does not provide a call operator
    ClangServer( const Specification& Specification = Specification() );
                                                      ^~~~~~~~~~~~~
1 error generated.
make[2]: **\* [CMakeFiles/clang-server.dir/main.cpp.o] Error 1
make[1]: **\* [CMakeFiles/clang-server.dir/all] Error 2
make: **\* [all] Error 2

`OS` : MacOS Yosemite 10.10.3
`CMake` : 3.3.2
`Compiler` : I have installed both `clang` and `gcc`, don't know which cmake used, how can I know? : 

`g++ --version`:
g++ (Homebrew gcc 4.9.2_1 --without-multilib) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

`clang --version`:
Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix

**Comment by chenhong805** [comment]
The arrow points to a wrong position, should be (Markdown deletes spaces, I use underline instead): 

ClangServer( const Specification& Specification = Specification() );
______________________________________________^~~~~~~~~~~~~

**Comment by yaruopooner** [comment]
I solved an issue, and committed it.

I corrected compile error just now.
An error was clang only.
I think the difference in the syntax checks of the compiler.
I will include clang in a build test.
But, not perfect test.
Because I don't have Mac environment.
Sorry.

**Comment by yaruopooner** [comment]
I have seen your log and have noticed.

### Problem-1

```
final: collected_library_apath =
final: library_apaths = 
```

This is not found clang library.
The clang-server need to use the LLVM library that was self- build.
Why is a self build done?
That's because it's necessary to apply patch for libclang.

### Problem-2

```
IT_SEARCH_PATH : /home/yaruopooner/work/llvm-build-shells/sh/clang-361/build
IT_SEARCH_PATH : /Users/jinhongc/.emacs.d/elpa/ac-clang-20150624.2000/clang-server
```

You have to edit a builder_sample.sh.
You designates path of self-build `libclang.so` at `DLIBRARY_PATHS`.

### Build step of clang-server
- LLVM self-build
  - Please use following scripts.
  - https://github.com/yaruopooner/llvm-build-shells
  - `git clone https://github.com/yaruopooner/llvm-build-shells.git` into your temporary directory.
  - You edit llvm-build-shells/sh/sample.sh. designates `patchPath`
  - The patch is `/Users/jinhongc/.emacs.d/elpa/ac-clang-20150624.2000/clang-server/patch/invalidate-mmap.patch`
  - Execute sample.sh(The script is build only. It isn't necessary to be installation.)
- clang-server build
  - You edit builder_sample.sh. designates `DLIBRARY_PATHS`
  - Build and sudo make install
