### ISSUE TITLE
Can't jump to macro definition

### ISSUE THREAD

**Issue by zijianyue** [yaruopooner/ac-clang#6]
Jump to const variable BCD OK, but can't jump to macro ABC's definition.Please confirm it.

``` c
#define ABC 5
const int BCD = 6;
int  main()
{
    int bb = BCD;
    return ABC;

}
```

**Comment by yaruopooner** [comment]
Thanks report.
I was confirmed same issue.
This problem depend on libclang.
libclang does not seem to be able to evaluate jump location in this case.
I'll look for solution method.

**Comment by yaruopooner** [comment]
Hi, I solved this issue.
Please update client lisp(v1.5.0) and server binary(v1.3.0).

**Comment by yaruopooner** [comment]
And added new feature.
It is possible jump to inclusion-file.

**Comment by zijianyue** [comment]
Great!!!!!!!!!!!!
