### ISSUE TITLE
The number of requests of the command queue reached the limit

### ISSUE THREAD

**Issue by zijianyue** [yaruopooner/ac-clang#7]
It happens after completion or jumping to definition failed several times, and this error can't recover though I invoke ac-clang-reset-server or ac-clang-deactivate or ac-clang-shutdown-server

**Comment by yaruopooner** [comment]
ok,I'll think about that way .

**Comment by zijianyue** [comment]
Add some information: I successed recover it in below order: ac-clang-deactivate -> ac-clang-shutdown-server -> ac-clang-launch-server -> ac-clang-activate, then ac-clang can work again ,but the auto-complete failed, I had to trigger completion manually three times before the result display.

**Comment by yaruopooner** [comment]
thanks report.
I'm testing reboot feature.
It will release within this week maybe.

**Comment by yaruopooner** [comment]
released v1.4.0, this is added server recovery feature.
